apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nokstella-Technologies/42-inception_of_things.git
    targetRevision: HEAD
    path: p3/confs  # Caminho onde estão os manifestos
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
