Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  config.vm.define "llima-ceS" do |server|
    server.vm.hostname = "llima-ceS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name   = "llima-ceS"
      vb.memory = "1024" 
      vb.cpus   = 1
    end

    server.vm.provision "shell" do |s|
      s.path = "scripts/install_k3s_server.sh"
    end
  end
end
