Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-24.04"
  
  
  config.vm.synced_folder ".", "/vagrant"
  config.vm.define "llima-ceS" do |server|
    server.vm.hostname = "llima-ceS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name   = "llima-ceS"
      vb.memory = "1024" 
      vb.cpus   = 1
    end

    server.vm.provision "shell" do |s|
      s.path = "scripts/install_k3s_server.sh"
    end
      # (Opcional) Caso queira copiar algum arquivo de configuração para /etc/k3s ou /home/vagrant:
    # server.vm.provision "file", source: "confs/meu-arquivo.yaml", destination: "/home/vagrant/meu-arquivo.yaml"
  end

  config.vm.define "llima-ceSW" do |worker|
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.hostname = "llima-ceSW"
    worker.vm.provider "virtualbox" do |vb|
      vb.name   = "llima-ceSW"
      vb.memory = "1024" 
      vb.cpus   = 1
    end

    worker.vm.provision "shell" do |s|
      s.path = "scripts/install_k3s_worker.sh"
    end
  end
end
#  /bar/log/syslog